# Generated by Django 2.1.1 on 2018-09-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180915_1252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
